<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>

    <!-- NuGet metadata -->
    <PackageId>AntalErvin19.FastRouter</PackageId>
    <Version>1.0.0</Version>
    <Authors>antalervin19</Authors>
    <Description>A lightweight convention-based API router for ASP.NET Core WebApplication. Declare routes in one place; handlers are discovered automatically from your Routes folder.</Description>
    <PackageTags>aspnetcore;router;minimal-api;routing;webapplication</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/antalervin19/FastRouter</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
